spring.application.name=Product Community Backend

#DATABASE CONFIGURATION
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/product_community_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#SERVER CONFIGURATION
server.port=${SERVER_PORT:8081}

#JWT CONFIGURATION
jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:86400000}

#CORS CONFIGURATION
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
